use_frameworks!

platform :ios, '8.0'

target 'CLNetWorkTools_Example' do
  pod 'CLNetWorkTools', :path => '../'

  target 'CLNetWorkTools_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
